name: CI Testing

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python all python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
     - name: Install dependencies
       run: pip install -r requirements.txt 
     - name: Test
       run: python -m unittest discover tests